# Generated by Django 3.2.12 on 2025-01-07 05:36

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0007_reportcard'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='id_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
