# Generated by Django 3.2.12 on 2025-01-07 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0008_auto_20250107_0536'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
            ],
        ),
    ]
